# Project :Google Stock Price Prediction (Time series) Using LSTM

# Read data

In [26]:
from warnings import filterwarnings
filterwarnings("ignore")
import pandas as mt
A = mt.read_csv("C:/Users/SHREE/Desktop/Data/Google_Stock_Price_Train.csv")

# Preview

In [3]:
A.head()

Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

# Missing data

In [4]:
A.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1258 entries, 0 to 1257
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    1258 non-null   object 
 1   Open    1258 non-null   float64
 2   High    1258 non-null   float64
 3   Low     1258 non-null   float64
 4   Close   1258 non-null   object 
 5   Volume  1258 non-null   object 
dtypes: float64(3), object(3)
memory usage: 59.1+ KB


# Get stock opening price

In [5]:
trd = A[["Open"]].values

In [6]:
import numpy as pd
pd.array(A[["Open"]])

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

# Preprocessing

In [7]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
mm.fit_transform(A[["Open"]])

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

# Create data in training and testing

In [8]:
xtrain = []
ytrain = []
for i in range(50,1258,1):
    xtrain.append(trd[i-50:i])
    ytrain.append(trd[i:i+1])

In [9]:
type(xtrain)

list

# Convert into array

In [10]:
xtr = pd.array(xtrain)

In [11]:
ytr = pd.array(ytrain)

# Create NN

In [12]:
from keras.models import Sequential
from keras.layers import LSTM,Dense,Dropout

In [13]:
nn = Sequential()
nn.add(LSTM(50,return_sequences=True,input_shape=(50,1)))
nn.add(LSTM(100,return_sequences=True))
nn.add(Dense(1))


In [14]:
nn.compile( optimizer='adam',loss="mean_squared_error")
nn.fit(xtr,ytr,epochs=10)

Epoch 1/10
38/38 [==============================] - 7s 74ms/step - loss: 308852.6562
Epoch 2/10
38/38 [==============================] - 2s 52ms/step - loss: 299793.1875
Epoch 3/10
38/38 [==============================] - 2s 51ms/step - loss: 294904.8125
Epoch 4/10
38/38 [==============================] - 2s 51ms/step - loss: 290452.9375
Epoch 5/10
38/38 [==============================] - 2s 52ms/step - loss: 286222.0938
Epoch 6/10
38/38 [==============================] - 2s 51ms/step - loss: 282125.8750
Epoch 7/10
38/38 [==============================] - 2s 51ms/step - loss: 278129.4062
Epoch 8/10
38/38 [==============================] - 2s 59ms/step - loss: 274214.0312
Epoch 9/10
38/38 [==============================] - 3s 67ms/step - loss: 270368.0000
Epoch 10/10
38/38 [==============================] - 2s 62ms/step - loss: 266578.9688


# Read data

In [15]:
import pandas as mt
tsd = mt.read_csv("C:/Users/SHREE/Desktop/Data/Google_Stock_Price_Test.csv")

# Preview

In [16]:
tsd

Date    Open    High     Low   Close     Volume
0    1/3/2017  778.81  789.63  775.80  786.14  1,657,300
1    1/4/2017  788.36  791.34  783.16  786.90  1,073,000
2    1/5/2017  786.08  794.48  785.02  794.02  1,335,200
3    1/6/2017  795.26  807.90  792.20  806.15  1,640,200
4    1/9/2017  806.40  809.97  802.83  806.65  1,272,400
5   1/10/2017  807.86  809.13  803.51  804.79  1,176,800
6   1/11/2017  805.00  808.15  801.37  807.91  1,065,900
7   1/12/2017  807.14  807.39  799.17  806.36  1,353,100
8   1/13/2017  807.48  811.22  806.69  807.88  1,099,200
9   1/17/2017  807.08  807.14  800.37  804.61  1,362,100
10  1/18/2017  805.81  806.21  800.99  806.07  1,294,400
11  1/19/2017  805.12  809.48  801.80  802.17    919,300
12  1/20/2017  806.91  806.91  801.69  805.02  1,670,000
13  1/23/2017  807.25  820.87  803.74  819.31  1,963,600
14  1/24/2017  822.30  825.90  817.82  823.87  1,474,000
15  1/25/2017  829.62  835.77  825.06  835.67  1,494,500
16  1/26/2017  837.81  838.00  827.01  832.15  2,973,900
17  1/27/2017  834.71  841.95  820.44  823.31  2,965,800
18  1/30/2017  814.66  815.84  799.80  802.32  3,246,600
19  1/31/2017  796.86  801.25  790.52  796.79  2,160,600

# Missing data

In [17]:
tsd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    20 non-null     object 
 1   Open    20 non-null     float64
 2   High    20 non-null     float64
 3   Low     20 non-null     float64
 4   Close   20 non-null     float64
 5   Volume  20 non-null     object 
dtypes: float64(4), object(2)
memory usage: 1.1+ KB


In [18]:
tsd[["Open"]]

Open
0   778.81
1   788.36
2   786.08
3   795.26
4   806.40
5   807.86
6   805.00
7   807.14
8   807.48
9   807.08
10  805.81
11  805.12
12  806.91
13  807.25
14  822.30
15  829.62
16  837.81
17  834.71
18  814.66
19  796.86

In [19]:
tsd.shape

(20, 6)

# Concat

In [20]:
Q = mt.concat([A,tsd])
Q.index = range(0,1278)

# Get stock opening price

In [21]:
Q = Q[["Open"]].values

# Create data in testing

In [22]:
xtest = []
for i in range(1258,1277,1):
    xtest.append(Q[i-50:i])

In [23]:
xts = pd.array(xtest)

# Prediction

In [24]:
xts.shape

(19, 50, 1)

In [25]:
nn.predict(xts)

array([[[31.645203],
        [48.22645 ],
        [50.426086],
        [50.733833],
        [50.77735 ],
        [50.783577],
        [50.78448 ],
        [50.78461 ],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.784637],
        [50.7